from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib import colors
import uuid
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

UPLOAD_DIR = os.path.join(
    BASE_DIR,
    "..",
    "..",
    "Notes"
)

os.makedirs(UPLOAD_DIR, exist_ok=True)


class PDFService:
    def __init__(self):
        self.styles = getSampleStyleSheet()

        self.body_style = ParagraphStyle(
            "BodyStyle",
            parent=self.styles["BodyText"],
            fontSize=12,
            leading=18,
            spaceAfter=8
        )

        self.title_style = ParagraphStyle(
            "TitleStyle",
            parent=self.styles["Title"],
            alignment=1,
            fontSize=24,
            textColor=colors.HexColor("#7C3AED"),
            spaceAfter=20
        )

    def _build_story(self, title, content):
        story = []

        # Title
        story.append(
            Paragraph(
                title,
                self.title_style
            )
        )

        # Subtitle
        story.append(
            Paragraph(
                "Generated by Flow AI",
                self.styles["Italic"]
            )
        )

        story.append(Spacer(1, 20))

        for line in content.split("\n"):
            line = line.strip()

            if not line:
                continue

            # H3
            if line.startswith("### "):
                story.append(
                    Paragraph(
                        line.replace("### ", ""),
                        self.styles["Heading3"]
                    )
                )

            # H2
            elif line.startswith("## "):
                story.append(
                    Paragraph(
                        line.replace("## ", ""),
                        self.styles["Heading2"]
                    )
                )

            # H1
            elif line.startswith("# "):
                story.append(
                    Paragraph(
                        line.replace("# ", ""),
                        self.styles["Heading1"]
                    )
                )

            # Bullet Points
            elif line.startswith("- "):
                story.append(
                    Paragraph(
                        f"• {line[2:]}",
                        self.body_style
                    )
                )

            # Normal Text
            else:
                story.append(
                    Paragraph(
                        line,
                        self.body_style
                    )
                )

            story.append(Spacer(1, 4))

        return story

    def create_pdf(self, title, content):
        file_id = str(uuid.uuid4())

        file_name = os.path.join(
            UPLOAD_DIR,
            f"notes_{file_id}.pdf"
        )

        doc = SimpleDocTemplate(file_name)

        story = self._build_story(
            title,
            content
        )

        doc.build(story)

        return file_id, file_name
